### ISSUE TITLE
generate_esphome_jura_yaml.py

### ISSUE THREAD

**Issue by DrJeff** [ryanalden/esphome-jura-component#2]
Is this file generate_esphome_jura_yaml.py necessary?
Or is it to just create the yaml for the wemos?

Please teach me I'm not getting this my 🤓 powers aren't working

**Comment by DrJeff** [comment]
Ok I get it now but cant get it to run `bitarray` not found even after adding the module

**Comment by ryanalden** [comment]
Thanks for the feedback -- I added an example to reflect the usage of generate_esphome_jura_yaml.py.

As for bitarray, how are you installing it?  I just verified it working on another, pristine machine (running macos 10.15).  Installed with  `sudo pip3 install bitarray`, running Python 3.7.3.  What environment are you running in?

**Comment by DrJeff** [comment]
Ok I cloned the directory on one of my machines and Viola! it works thanks for this now time to play. I believe it's how my python install was on my Mac

Thanks for this The only issue is my machine Ena 9 loses power on the service port on shutdown so probably going to need to use 2 relays internally for the power. mainly to turn back on the unit and I will probably run the unit off a 5V power source internally.
