### ISSUE TITLE
Newbee

### ISSUE THREAD

**Issue by ronniebee** [ryanalden/esphome-jura-component#5]
Hi Ryan,

Though it is not an issue your assistance will be appreciated. I make use of ESPhome in my Homeassistant.
After spending > 20 hours with my esp32 board I was not able to get my Jura j5 to respond.
Tried to use your yaml code ( copied it into the ESPhome configuration) but that led to no result on this esp board.. (Yes I'm a newbee with these boards :-) )  and so decided to buy the wemos d1 mini.

After setting-up the hardware can I then copy your YAML file in my ESPhome environment ( by using of course my own wifi credentials) and than install on the Wemos?  Or am I missing something?

Can you please advice?

Looking forward ypur reply.

Regards,

Ronald

**Comment by ryanalden** [comment]
Hi Ronald,

Sorry to hear you struggled with your ESP32.

If I'm understanding you correctly, your question is about getting the initial ESPHome install onto the D1 mini (?). To do so, I suggest the initial flash be done via USB using ESPHome-Flasher, using my yaml that's been adapted to your environment, i.e. using your wifi SSID, password. After the device comes up on the WiFi you can subsequently flash it wirelessly.

I suggest experimenting with ESPhome and your D1 mini with some simpler projects, so you get a good feel for how ESPhome works and then after you feel comfortable you can try talking to the Jura.

Let me know if I didn't understand your question :)

**Comment by ronniebee** [comment]
Hi Ryan, thx for your reply, much appreciated. I think I understand the basics (I think :-) ). Did a small arduino course on sketches, upload etc. The ESP solution looks a lot easier.  I did manage to put together the Wemos and convertor according to your instructions ( checked it multiple times)  and plugged it into my Jura J5 (not the 6).

What I did was create an ESPhome item Called it Jura.

![Schermafbeelding 2021-12-10 om 18 53 44](https://user-images.githubusercontent.com/7029899/145619574-24ceaad8-eda0-47d7-b236-cc87bf85a7a3.png)

I than created the YAML. The strange thing is that it did not accept the TX and RX pin with D1 and D2. I changed it in GPIO1 and GPIO2 which was accepted. Don't know if this is correct. 
All sensor show up in HA, the board  is online but no respons when I slide  the " make coffee "button. I changed the tx/rx on my jura but no effect. 

I also made a file  /config/esphome/jura_coffee.h and copied the content of the file into it. The YAML als failed without this file.

#include "esphome.h"

class JuraCoffee : public PollingComponent, public UARTDevice {
 Sensor *xsensor1 {nullptr};
 Sensor *xsensor2 {nullptr};
etc 
etc


My YAML:

substitutions:
  devicename: jura
  friendly_name: Coffee Machine
  device_description: Jura Coffee Machine in Kitchen

esphome:
  name: $devicename
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m
  platformio_options:
    upload_speed: 115200
  includes:
    - jura_coffee.h  

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "9b2b8a99952a51f4187ceaaf4bc96523"

wifi:
  ssid: "Prixxxxx"
  password: "Sxxxxxxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jura Fallback Hotspot"
    password: "C1Dq7N2ThZiG"

captive_portal:


uart:
  tx_pin: GPIO1
  rx_pin: GPIO2
  baud_rate: 9600
  id: uart_bus

# UART bytes below have been generated with generate_esphome_jura_yaml.py
# Tested with a Jura Impressa J6

switch:
  - platform: template
    name: 'Coffee Machine'
    icon: "mdi:coffee-maker"
    id: jura_on_off_switch
    turn_on_action:
      - uart.write: [0xDF, 0xDB, 0xDB, 0xDF]  ## 'A'
      - delay: 8ms
      - uart.write: [0xFB, 0xFF, 0xDB, 0xDF]  ## 'N'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xFF, 0xDB]  ## ':'
      - delay: 8ms
      - uart.write: [0xDB, 0xDB, 0xFF, 0xDB]  ## '0'
      - delay: 8ms
      - uart.write: [0xDF, 0xDB, 0xFF, 0xDB]  ## '1'
      - delay: 8ms
      - uart.write: [0xDF, 0xFF, 0xDB, 0xDB]  ## '\r'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xDB, 0xDB]  ## '\n'

    turn_off_action:
      - uart.write: [0xDF, 0xDB, 0xDB, 0xDF]  ## 'A'
      - delay: 8ms
      - uart.write: [0xFB, 0xFF, 0xDB, 0xDF]  ## 'N'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xFF, 0xDB]  ## ':'
      - delay: 8ms
      - uart.write: [0xDB, 0xDB, 0xFF, 0xDB]  ## '0'
      - delay: 8ms
      - uart.write: [0xFB, 0xDB, 0xFF, 0xDB]  ## '2'
      - delay: 8ms
      - uart.write: [0xDF, 0xFF, 0xDB, 0xDB]  ## '\r'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xDB, 0xDB]  ## '\n'
    optimistic: true
    assumed_state: true

  - platform: template
    name: 'Make Hot Water'
    icon: "mdi:cup-water"
    id: jura_make_hot_water
    turn_on_action:
      - uart.write: [0xFB, 0xDF, 0xDB, 0xDF]  ## 'F'
      - delay: 8ms
      - uart.write: [0xDF, 0xDB, 0xDB, 0xDF]  ## 'A'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xFF, 0xDB]  ## ':'
      - delay: 8ms
      - uart.write: [0xDB, 0xDB, 0xFF, 0xDB]  ## '0'
      - delay: 8ms
      - uart.write: [0xFB, 0xDF, 0xFF, 0xDB]  ## '6'
      - delay: 8ms
      - uart.write: [0xDF, 0xFF, 0xDB, 0xDB]  ## '\r'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xDB, 0xDB]  ## '\n'

  - platform: template
    name: 'Make Coffee'
    icon: "mdi:coffee"
    id: jura_make_coffee
    turn_on_action:
      - uart.write: [0xFB, 0xDF, 0xDB, 0xDF]  ## 'F'
      - delay: 8ms
      - uart.write: [0xDF, 0xDB, 0xDB, 0xDF]  ## 'A'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xFF, 0xDB]  ## ':'
      - delay: 8ms
      - uart.write: [0xDB, 0xDB, 0xFF, 0xDB]  ## '0'
      - delay: 8ms
      - uart.write: [0xDF, 0xFB, 0xFF, 0xDB]  ## '9'
      - delay: 8ms
      - uart.write: [0xDF, 0xFF, 0xDB, 0xDB]  ## '\r'
      - delay: 8ms
      - uart.write: [0xFB, 0xFB, 0xDB, 0xDB]  ## '\n'

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: template
    id: num_single_espresso
    name: "Single Espressos Made"
    accuracy_decimals: 0
    lambda: "return {};"

  - platform: template
    id: num_double_espresso
    name: "Double Espressos Made"
    accuracy_decimals: 0
    lambda: "return {};"

  - platform: template
    id: num_coffee
    name: "Coffees Made"
    accuracy_decimals: 0
    lambda: "return {};"

  - platform: template
    id: num_double_coffee
    name: "Double Coffees Made"
    accuracy_decimals: 0
    lambda: "return {};"

  - platform: template
    id: num_clean
    name: "Cleanings Performed"
    accuracy_decimals: 0
    lambda: "return {};"

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome version"
    
  - platform: template
    id: tray_status
    name: "Tray Status"
    lambda: "return {};"
    
  - platform: template
    id: tank_status
    name: "Water Tank Status"
    lambda: "return {};"

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

# Custom component to poll coffee machine counters & status
custom_component:
- lambda: |-
    auto my_jura = new JuraCoffee(id(uart_bus),id(num_single_espresso),id(num_double_espresso),id(num_coffee),id(num_double_coffee),id(num_clean),id(tray_status),id(tank_status));
    App.register_component(my_jura);
    return {my_jura};
``


Maybe you can give me some advice?

Looking forward your reply.

Regard,

Ronald

**Comment by ryanalden** [comment]
Great! Glad to hear it.

**Comment by ronniebee** [comment]
The one thing I don't quite onderstand is the " generate_esphome_jura_yaml.py"
Where to put this command?  

(Nb works flawless, kids were amazed :-)... )

**Comment by ryanalden** [comment]
It's a Python script. You must have Python installed in order to run it. The script expects a command to be provided (for example, "AN:01"), and will generate the yaml needed in ESPHome to send that command to the Jura. An example of this is provided on my main esphome-jura-component GitHub page.

The script is provided so that those with different models of Jura can experiment with sending other commands to their machines. Not all machines accept the same commands.

**Comment by ronniebee** [comment]
Great! I'll give it a try. Many thx, my friends were amazed that my old machine was made smart :-)
